### ISSUE TITLE
Can't deploy Graylog, Relation with MongoDB doesn't work

### ISSUE THREAD

**Issue by jonatasbaldin** [canonical/graylog-operator#21]
While trying to create the Relation between Graylog and MongoDB, I got this error:

```bash
application-mongodb: 17:40:48 ERROR unit.mongodb/2.juju-log database:9: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 280, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-2/charm/venv/ops/main.py", line 402, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-2/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-2/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-2/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-2/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 213, in on_database_relation_changed
    self.standalone_uri)
AttributeError: 'MongoDBCharm' object has no attribute 'standalone_uri'
```

My juju version is: `2.9-rc6-catalina-amd64`.

**Comment by Abuelodelanada** [comment]
Hi @jonatasbaldin 

Please, could you detail all the steps you took to arrive at this error?

**Comment by jonatasbaldin** [comment]
I followed the exact steps on the [project README](https://charmhub.io/graylog-k8s), the only difference being using Kind as the Kubernetes cluster.

Just nuked my cluster and tried again, got the same error.

**Comment by mthaddon** [comment]
I've tried this on microk8s with juju 2.9-rc6,. and I got a different failure:

```
application-graylog: 13:22:07 INFO juju.worker.caasoperator.uniter.graylog/0 awaiting error resolution for "relation-changed" hook
application-graylog: 13:22:17 INFO juju.worker.caasoperator.uniter.graylog/0 awaiting error resolution for "relation-changed" hook
application-graylog: 13:22:18 ERROR unit.graylog/0.juju-log mongodb:3: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 223, in <module>
    main(GraylogCharm)
  File "/var/lib/juju/agents/unit-graylog-0/charm/venv/ops/main.py", line 401, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-graylog-0/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-graylog-0/charm/venv/ops/framework.py", line 234, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-graylog-0/charm/venv/ops/framework.py", line 678, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-graylog-0/charm/venv/ops/framework.py", line 723, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 127, in _on_mongodb_relation_changed
    self._configure_pod()
  File "./src/charm.py", line 215, in _configure_pod
    spec = self._build_pod_spec()
  File "./src/charm.py", line 173, in _build_pod_spec
    'GRAYLOG_HTTP_PUBLISH_URI': self.external_uri,
  File "./src/charm.py", line 56, in external_uri
    ingress = str(self.model.get_binding('graylog').network.ingress_address)
  File "/var/lib/juju/agents/unit-graylog-0/charm/venv/ops/model.py", line 506, in network
    self._network = Network(self._backend.network_get(self.name, self._relation_id))
  File "/var/lib/juju/agents/unit-graylog-0/charm/venv/ops/model.py", line 545, in __init__
    for address_info in interface_info.get('addresses', []):
TypeError: 'NoneType' object is not iterable
application-graylog: 13:22:18 ERROR juju.worker.caasoperator.uniter.graylog/0.operation hook "mongodb-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

This left MongoDB in `hook failed: "mongodb-relation-changed"`.

The steps I took were (I used charms from the charm store/charmhub where possible):
```
juju add-model graylog micro
juju deploy cs:~charmcraft/graylog
cd ~/repos/
mkdir mongodb-operator
cd mongodb-operator/mongodb-operator/
git pull
charmcraft build
juju deploy ./mongodb.charm
juju deploy ./mongodb.charm --resource mongodb-image=mongo:4.4.1
juju deploy cs:~charmcraft/elasticsearch
juju add-unit -n 2 mongodb
# Wait for juju status to settle, mongodb and elasticsearch active and idle
# graylog blocked with message "Need mongodb and Elasticsearch relations."
juju add-relation graylog mongodb
juju add-relation graylog elasticsearch
```

**Comment by Abuelodelanada** [comment]
Thanks @jonatasbaldin @mthaddon, We'll take a look. 
Please, remember this isn't production ready charm yet.

**Comment by jonatasbaldin** [comment]
hey @Abuelodelanada! is there a release date and/or roadmap for a production-ready Charm?

**Comment by Abuelodelanada** [comment]
Hi folks,

@mthaddon  I have a work in progress PR to fix the error you found in this PR #24 

@jonatasbaldin Please, may you try deploying again using code in PR #24 ?

**Comment by jonatasbaldin** [comment]
hey @Abuelodelanada, I'm unfortunately not working with the Opertor Framework anymore, I won't be able to test it :(

**Comment by Abuelodelanada** [comment]
Do not worry @jonatasbaldin, thank you very much for your testing.
The best for you in the next steps!
